## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# List here the tasks and the commands for this workflow
# then run `fzz` to start to work.

- name: quick checks
  run: 
    - echo "{{relative_path}}" >> /tmp/files-changed
    - make test
    - make format
    - make lint
    - xargs -I{} sh -c 'git add {} || true' < /tmp/files-changed
    - echo "" > /tmp/files-changed
  change: '**/*.py'
  ignore:
    # ignore all python compiled files
    - '__pycache__'
    - '*.pyc'

- name: start app
  run: 
    - make start
  change: '**/*.py'
  ignore:
    # ignore all python compiled files
    - '__pycache__'
    - '*.pyc'

